version: '3.2'

services:
   db:
     image: mysql:5.7
     volumes:
       - type: bind
         source: .db_data
         target: /var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     volumes:
       - type: bind
         source: ./build
         target: /var/www/html/wp-content/themes/theme
       - type: bind
         source: ./.uploads
         target: /var/www/html/wp-content/uploads
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
