version: '3.2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpstandalone:
    depends_on:
      - db
    build: https://github.com/pawelkorus/docker-php-builtin-server.git
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - wordpress:/root-dir
    environment:
      LOCAL_USER_ID: "1000"

  wp-cli:
    build: https://github.com/pawelkorus/docker-wp-cli.git
    volumes:
      - wordpress:/root-dir
    environment:
      LOCAL_USER_ID: "1000"

volumes:
  db:
    driver: local
  wordpress:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/.wordpress
